### PR TITLE
Upgrade export task context and general export fixes

### PR DESCRIPTION
**Pull request by anthony-sarkis**
Summary

1. **Make export from tasks work as expected.** Meaning it pulls from tasks not files. This is becuase now that we have streaming, the concept of a file being associated with a singular job is ill-defined. Further it opens the ability to use task orientated filters!
2. It also happens to fix the one-off case of job_id not being populated unless annotation was completed, effectively meaning "ann_is_true" was forced on, but without actually using that flag, which is of course bad.
3. Fix a variety of > instead of >= and refactor to avoid in future. 
Note: It's possible this could have downstream effects, but unless there was some reason (I can't think of one) that we actually did want ">" for these, then this fix should still be correct, and we can do further fixes for downstream issues.
4. Small fixes on export conditions
5. Properly call `check_export_permissions_and_status()` in the immediate return case
6. Add a wip test case for this path since it's different from the existing working dir test case

A past hesitancy with moving to task abstraction was if we should actually export the task objects. But for now, by simply converting back to the same file list structure, it works. And we can explore exporting more task specific data later if needed.

Pablo, the test case mostly works but for some reason `instance_list` is not being populated. It's successfully getting the file though. https://github.com/diffgram/diffgram/runs/3680036283?check_suite_focus=true#step:17:109 
I'm not sure if I'm using the utility function correctly, maybe can I get your help there when you can please?

### CODE REVIEW

**Comment by PJEstrada** [comment]
Hey @anthony-sarkis ! Change look great! The `log_has_error` function is a great idea! Is a lot more verbose and easier to understand. All other changes to the export look good to me too!

I'll take a look at the failing test case now and commit the fix

**Comment by anthony-sarkis** [comment]
Thanks Pablo!!

**Comment by PJEstrada** [comment]
Tests should now be fixed Anthony. Issue was just that the export mock was missing the `file_comparison_mode` field

**Review by PJEstrada — APPROVED** [review]

**Comment by anthony-sarkis** [comment]
Amazing! Good find Pablo!!

**Comment by anthony-sarkis** [comment]
Thank you very much!

**Comment by PJEstrada** [comment]
Pleasure Anthony! I think with this we can merge it once tests pass :)

**Pull request merged**
