### PR TITLE
RIght Click Focus Instance

### PR DESCRIPTION
**Pull request by PJEstrada**
- Allow to focus instance with right click context menu
- Allot to focus instance with holding F+clicking instance

### CODE REVIEW

**Comment by anthony-sarkis** [comment]
Awesome! 😊

**Comment by anthony-sarkis** [comment]
@PJEstrada I made this suggestion for consideration [Suggestion: Focus key on hover](https://github.com/diffgram/diffgram/pull/726/commits/c28732ffecd737ca07ec817e2aed2f768db4fbdd)

**Comment by PJEstrada** [comment]
Thanks Anthony! The your hotkey idea is much better! Merging now :)

**Comment by anthony-sarkis** [comment]
Cool, thanks Pablo!

**Pull request merged**
