### PR TITLE
Small improvements to the main toolbar

### PR DESCRIPTION
**Pull request by vitalii-bulyzhyn**
This will be a small PR:
-  remove useless DB icon from menu
- add drop down to the menu
- tests

### CODE REVIEW

**Comment by PJEstrada** [comment]
Super thanks Vitalii! Let me know when it's ready so I can proceed with review

**Comment by vitalii-bulyzhyn** [comment]
@PJEstrada of course, will be working on this on as a secondary priority

**Review by PJEstrada — COMMENTED** [review]
Hey Vitalii!

Code looks good thanks for this!

Just one small thing:

When I click the project title it seems to open a blank space:

image


In previous versions this was just a text so I'm not sure if this is something you wanted to add that maybe is not working properly? Other from this the rest looks great !

**Comment by vitalii-bulyzhyn** [comment]
@PJEstrada I fixed the bug, should be working fine now

**Comment by PJEstrada** [comment]
1. When changing project on the home screen, the home screen component is not updating.
2. Hide the current project from the project selection list.

**Comment by PJEstrada** [comment]
Hey Vitalii!

For this one I'm just having this issue now when I'm no the job detail page:

image


The toolbar does not seem to render for some reason:


I also get this error on the chrome console, maybe it helps:

image

**Comment by PJEstrada** [comment]
Thanks Vitalii! I'm merging this now :)

**Review by PJEstrada — APPROVED** [review]

**Pull request merged**
