### PR TITLE
DAD-244 Workflow Builder

### PR DESCRIPTION
**Pull request by PJEstrada**
- [x] Create UI Components for Basic Flow Support (Upload => Label => Export)
- [x] Define App Concepts for Process Builder (Triggers, Actions, Conditionals, Complete Conditions, etc)
- [x] Add Backend Support for Basic Flow (Upload => Label => Export)
- [x] Add Rabbit MQ To Diffgram Services
- [x] Separate Actions Processor Into a Separate Service
- [x] Change Flow Execution to an Event Driven Architecture.

### CODE REVIEW

**Review by anthony-sarkis — APPROVED** [review]

**Comment by vitalii-bulyzhyn** [comment]
@anthony-sarkis @PJEstrada I've finished adding global attributes to the text interface, please test this thing out before meging

**Comment by anthony-sarkis** [comment]
Thanks Vitalii!

**Comment by PJEstrada** [comment]
> @anthony-sarkis @PJEstrada I've finished adding global attributes to the text interface, please test this thing out before meging

Thanks Vitalii! Already tested and everything working smoothly :) Will merge in a bit after pushing some small fixes

**Comment by PJEstrada** [comment]
Docs: https://diffgram.readme.io/docs/workflows

**Pull request merged**
