### PR TITLE
Aniketzz oci connection

### PR DESCRIPTION
**Pull request by aniketzz**
OCI Connection added in install.py

### CODE REVIEW

**Comment by PJEstrada** [comment]
Hi @aniketzz,

Thank you so much for your contribution.

Since this is the first contribution you add to the project, I'm sharing with you some useful links:

https://diffgram.readme.io/docs/git-tags-for-issues
https://diffgram.readme.io/docs/code-review-guidelines

As for this specific PR, I'm still not sure if you are fully finished or not, But when you are ready to merge it so core maintainers can review it, please add the "ready_to_merge" tag to the PR and also request the review of one or more of the core contributors depending on the section of code being changed:

https://diffgram.readme.io/docs/diffgram-core-maintainers

**Comment by aniketzz** [comment]
Hi,

It seems like we will have to create a script under the `shared` directory called `data_tools_core_oci.py`.  It would be great if you could help me with the script. 

Without that script, I am getting the below error while doing the registration.
docker screenshot

**Comment by PJEstrada** [comment]
Hi @aniketzz,

In order to add this class the best approach is to use one of the existing implementations as a guide. I would suggest you check `data_tools_core_azure.py`

The class has to implement the follwing functions for it to work correctly:

1. `create_resumable_upload_session`
2. `transmit_chunk_of_resumable_upload`
3. `download_from_cloud_to_local_file`
4. `upload_to_cloud_storage`
5. `upload_from_string`
6. `download_bytes`
7. `get_image`
8. `build_secure_url`
9. `get_string_from_blob`
10. `rebuild_secure_urls_image`

That will add the support for uploading, downloading, reading and writing bytes into Oracle. Each funcion will have implementation details specific to Oracle's SDK. But you can check `data_tools_core_azure.py` to get an idea of what each function should achieve.

Once you added all the function, the final step would be to add the constructor on the `__init__` function for the `Data_tools` class in the file `data_tools_core.py`.

Take a look at the existing implementations and once you have any specific questions for any of the functions required I can gladly provide more insights to solve your questions  :)

**Comment by anthony-sarkis** [comment]
I'm going to close this for time being. Please re-open if this becomes active again! :)

**Pull request closed without merging**
