### PR TITLE
Dataset Explorer

### PR DESCRIPTION
**Pull request by PJEstrada**
This is the V1 for the dataset explorer feature. Some things aimed to be released here are:

- Support for multiple datasets rendering in annotation core
- Support for multiple canvas renders
- Better support for Model Run Concepts
- Better data browsing with instances previews.

### CODE REVIEW

**Comment by anthony-sarkis** [comment]
Really great progress Pablo!! Thank you :)

**Comment by PJEstrada** [comment]
E2E tests should be passing now. I'm only pending some fixes related to the frame preview on the video player and I think the branch will be ready to merge. Let me know if you find any this you might want me to change or improve !

**Comment by PJEstrada** [comment]
All tests passing now :) Will merge in a little while.

**Comment by anthony-sarkis** [comment]
This is an incredible new feature!!!   Now we can compare datasets, model run performance, etc.

Posting this here as a quick preview until the full sample and article etc are ready:

image

**Pull request merged**
