### PR TITLE
Connection Testing Improvements

### PR DESCRIPTION
**Pull request by PJEstrada**
Add better connection testing both on the install.py script as well as the connection testing on the UI.

This will add permissions testing for S3, GCP and Azure providers.

### CODE REVIEW

**Comment by PJEstrada** [comment]
Now Install script will show the following message for connection testing: 

image

**Comment by PJEstrada** [comment]
Now the install script will show the following messages:

image

**Comment by PJEstrada** [comment]
For connections now we can see more detailed errors on permission when doing the test connection button:

image

**Comment by anthony-sarkis** [comment]
> Now the install script will show the following messages:
> 
> image

This is great Pablo!!!!   Now we can catch these connection and credential setup stuff right away instead of it "looking like it's working" but that part potentially being incorrectly configured!! Super work!

**Pull request merged**
