### PR TITLE
Display new statuses on job page

### PR DESCRIPTION
**Pull request by vitalii-bulyzhyn**
In this PR:
- Display new icons for new statuses on the task list
- Display new statuses on the stats

### CODE REVIEW

**Comment by vitalii-bulyzhyn** [comment]
@PJEstrada do you think I need to add extra units for this?

**Comment by PJEstrada** [comment]
Hey Vitalii! If unit tests already exist I would just add any extra assertions to cover this code. If the component tests are non existent then I think its always good to add them. As long term goal we would like to eventually reach 90% tests code coverage so any steps towards that goal are always a good idea :)

**Comment by vitalii-bulyzhyn** [comment]
Gotcha

**Review by PJEstrada — APPROVED** [review]
Hey Vitalii!

Thanks for the improvements here I see everything good now. Feel free to merge this one to master now

**Pull request merged**
